### ISSUE TITLE
Exception on i.s.c

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#107] opened 2017-06-08 11:25 UTC
### Steps to reproduce

This happened in i.s.c

1. Create a user with People app
2. Add a user account for this person using UserAdmin
3. Try to see this user in UserAdmin

### Expected result

You shoud see the user admin page about the user

### Actual result

You get an exception from Sign In:

```
GET http://inside.starcounter.com/__insidestarcountercom/xxx

System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'ResetPassword_Enabled' in 'SystemUserAuthenticationSettings'.
Version: 2.3.0.6089.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.GetAndCacheValue(Json parent) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 47
   at Starcounter.XSON.NewtonSoftSerializer.GetValue[T](Property`1 template, Json parent, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 575
   at Starcounter.XSON.NewtonSoftSerializer.SerializeBool(Json json, Template template, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 139
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 240
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 272
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter\Transaction.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 240
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 240
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 272
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.NewtonSoftSerializer.SerializeArray(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 320
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 240
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.NewtonSoftSerializer.<>c__DisplayClass10_1.<Serialize>b__0() in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 79
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, TextWriter textWriter, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 82
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 61
   at Starcounter.Internal.PuppetRestHandler.CreateJsonBodyResponse(Session session, Json root) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 201
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Simplified.Ring3.EmailAddress.get_EMail()
   at SignIn.SystemUserAuthenticationSettings.get_ResetPassword_Enabled_() in c:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterPrefabs\SignIn\src\SignIn\ViewModels\SystemUserAuthenticationSettings.json.cs:line 20
   at lambda_method(Closure , Json )
HResult=-2147467261

More information about this error may be available in the server error log.
```

##### Involved apps' version

https://github.com/StarcounterApps/SignIn/commit/8c10b2f1c716bade691a33beee5128cff2a33618
https://github.com/StarcounterApps/UserAdmin/commit/20f04b7ef8939d991f08fdf65a163f4857a901c2

**Comment by warpech** [comment] 2017-06-08 15:25
@PatrykSzwer can you pls investigate? The bottom of the stack trace suggests that it is related with the recent changes regarding blending of Sign In with User Admin (#99).

**Comment by PatrykSzwer** [comment] 2017-06-09 07:58
@warpech I tried to reproduce this with newest builds from develop branches, without success. When I was trying to remake this bug in inside.starcounter.com I engaged with other issues that made this reproduction impossible (Authentication errors, probably my account doesn't have required permissions). Please confirm if You managed to reproduce this on newest builds.

**Comment by PatrykSzwer** [comment] 2017-06-19 12:37
Since is no longer occurring, I'm closing this issue.

**Closed by PatrykSzwer** 2017-06-19 12:37 UTC
